language: ruby
before_install:
  - gem update --system 1.6.2 # Downgrade to the same version installed on the server
  - gem --version
jobs:
  include:
    - stage: test
      script: bundle exec rake
      name: Run code tests
    - script: bundle exec ./postcodes.rb --test
      name: Test postcodes.csv
    - script: bundle exec ./parse-members.rb --test
      name: Test members datafiles 
